---
abstract: 'Plurk API'
author:
  - 'Cornelius, C<< <cornelius.howl at gmail.com> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Text::Greeking::zh_TW: 0.0.4
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Plurk
no_index:
  directory:
    - inc
    - t
requires:
  DateTime::Tiny: 0
  HTTP::Cookies: 0
  JSON: 0
  LWP::UserAgent: 0
  Test::More: 0
  common::sense: 0
resources:
  license: http://dev.perl.org/licenses/
version: 9.32115
