--- #YAML:1.0
name:               Net-Plurk
version:            0.06
abstract:           The great new Net::Plurk!
author:
    - Cheng-Lung Sung <clsung@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    AnyEvent::HTTP:       0
    DateTime::Format::Strptime:  0
    JSON::Any:            0
    Moose:                0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
